//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departament()
        {
            this.Person1 = new HashSet<Person1>();
        }
    
        public int departamentId { get; set; }
        public string name { get; set; }
        public int createdBy { get; set; }
        public int updatedBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime udaedAt { get; set; }
        public int PersonpersonaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person1> Person1 { get; set; }
    }
}
