//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int RolId { get; set; }
        public int salary { get; set; }
        public int bonusSalary { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
        public int createdBy { get; set; }
        public int updatedBy { get; set; }
        public int availableDays { get; set; }
        public int daysPerYear { get; set; }
        public int workingDay { get; set; }
    }
}
